use std::fs;
use anyhow::Result;
use host::{ create_zkp_age_over_18, create_zkp_jwt_valid, get_age_from_jwt };
// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
// The ELF is used for proving and the ID is used for verification.
use methods::{ AGE_OVER_18_ID };
// Double colons (::) are called path separators. Used to access items (functions, types, constants etc.)
// inside modules enums or crates.

mod api; // This makes host/src/api.rs availanle

fn main() -> Result<()> {
    // Initialize tracing. In order to view logs, run `RUST_LOG=info cargo run`
    tracing_subscriber
        ::fmt()
        .with_env_filter(tracing_subscriber::filter::EnvFilter::from_default_env())
        .init();

    let filepath_jwt_payload: &str = "PIDVCpayload.json";
    let age: i32 = get_age_from_jwt(filepath_jwt_payload);
    let filepath_jwt_encoded: &str = "PIDVCencoded";
    let jwt = fs::read_to_string(filepath_jwt_encoded).expect("Not able to read file");

    let zkp = create_zkp_age_over_18(&jwt, &age);

    match zkp {
        Ok(zkp) => {
            let journal: bool = zkp.journal
                .decode()
                .expect(
                    "ERROR: Occured while deserializing journal output. It should deserialize into the same types (& order) that it was written"
                );

            zkp.verify(AGE_OVER_18_ID).expect(
                "ERROR: Occured while verfifying receipt. Image ID might be wrong."
            );

            println!("{journal}");
        }
        Err(e) => eprintln!("{e}"),
    }

    // The receipt was verified at the end of proving, but the below code is an
    // example of how someone else could verify this receipt.
    //receipt.verify(AGE_OVER_18_ID).unwrap();

    Ok(())
}

// ------- HTTP entry point -------

// Må ha med #[tokio::main] fordi fordi start_server() er async
// #[tokio::main]
// async fn main() -> anyhow::Result<()> {
//     // Start the HTTP server (this never returns until you stop it)
//     api::start_server().await;
//     Ok(())
// }
