use anyhow::Result;
use host::{ create_zkp_age_over_18, get_age_from_jwt };
// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
// The ELF is used for proving and the ID is used for verification.
use methods::{ AGE_OVER_18_ID, JWT_VALIDATOR_ELF, JWT_VALIDATOR_ID };
// Double colons (::) are called path separators. Used to access items (functions, types, constants etc.)
// inside modules enums or crates.

// For untyped json values.
// Burde gå over til use serde::{Deserialize, Serialize}; for strongly typed data structures

fn main() -> Result<()> {
    // Initialize tracing. In order to view logs, run `RUST_LOG=info cargo run`
    tracing_subscriber
        ::fmt()
        .with_env_filter(tracing_subscriber::filter::EnvFilter::from_default_env())
        .init();

    // An executor environment describes the configurations for the zkVM
    // including program inputs.
    // A default ExecutorEnv can be created like so:
    // `let env = ExecutorEnv::builder().build().unwrap();`
    // However, this `env` does not have any inputs.
    //
    // To add guest input to the executor environment, use
    // ExecutorEnvBuilder::write().
    // To access this method, you'll need to use ExecutorEnv::builder(), which
    // creates an ExecutorEnvBuilder. When you're done adding input, call
    // ExecutorEnvBuilder::build().

    let filepath: &str = "PIDVCpayload.json";
    let age: i32 = get_age_from_jwt(filepath);
    let zkp = create_zkp_age_over_18(&age);

    match zkp {
        Ok(zkp) => {
            let journal: String = zkp.journal
                .decode()
                .expect(
                    "ERROR: Occured while deserializing journal output. It should deserialize into the same types (& order) that it was written"
                );

            zkp.verify(AGE_OVER_18_ID).expect(
                "ERROR: Occured while verfifying receipt. Image ID might be wrong."
            );

            println!("{journal}");
        }
        Err(e) => eprintln!("{e}"),
    }

    // The receipt was verified at the end of proving, but the below code is an
    // example of how someone else could verify this receipt.
    //receipt.verify(AGE_OVER_18_ID).unwrap();

    Ok(())
}
