// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
// The ELF is used for proving and the ID is used for verification.
use methods::{ METHOD_ELF, METHOD_ID, JWT_VALIDATOR_ELF, JWT_VALIDATOR_ID };
// Double colons (::) are called path separators. Used to access items (functions, types, constants etc.)
// inside modules enums or crates.
use risc0_zkvm::{ default_prover, ExecutorEnv };
use std::fs;
// For untyped json values.
// Burde gå over til use serde::{Deserialize, Serialize}; for strongly typed data structures
use serde_json::Value;
use chrono::{ NaiveDate, Datelike, Utc };

fn main() {
    // Initialize tracing. In order to view logs, run `RUST_LOG=info cargo run`
    tracing_subscriber
        ::fmt()
        .with_env_filter(tracing_subscriber::filter::EnvFilter::from_default_env())
        .init();

    // An executor environment describes the configurations for the zkVM
    // including program inputs.
    // A default ExecutorEnv can be created like so:
    // `let env = ExecutorEnv::builder().build().unwrap();`
    // However, this `env` does not have any inputs.
    //
    // To add guest input to the executor environment, use
    // ExecutorEnvBuilder::write().
    // To access this method, you'll need to use ExecutorEnv::builder(), which
    // creates an ExecutorEnvBuilder. When you're done adding input, call
    // ExecutorEnvBuilder::build().

    let filepath = "PIDVCpayload.json";
    println!("In file {}!", filepath);

    let contents = fs::read_to_string(filepath).expect("Not able to read file.");
    let json: Value = serde_json::from_str(&contents).expect("Invalid JSON structure.");

    // Navigate to birth_date field
    let birth_date_str = json["vc"]["credentialSubject"]["birth_date"]
        .as_str()
        .ok_or("Missing birthdate");

    println!("Birth date: {}", birth_date_str.unwrap_or("unknown"));

    // Parse date and compute age
    // NaiveDate represents a calendar date without any timezone information.
    let birth_date = NaiveDate::parse_from_str(
        birth_date_str.unwrap_or("unknown"),
        "%Y-%m-%d"
    ).expect("Invalid date string.");
    let today = Utc::now().date_naive();
    // Subtract 1 more if the person hasn't had their birthday this year yet.
    let age =
        today.year() -
        birth_date.year() -
        (if (today.month(), today.day()) < (birth_date.month(), birth_date.day()) { 1 } else { 0 });

    let env = ExecutorEnv::builder().write(&age).unwrap().build().unwrap();

    // Obtain the default prover.
    let prover = default_prover();

    // Proof information by proving the specified ELF binary.
    // This struct contains the receipt along with statistics about execution of the guest
    // let prove_info = prover.prove(env, METHOD_ELF).unwrap();

    let prove_info = prover.prove(env, JWT_VALIDATOR_ELF).unwrap();
    // extract the receipt.
    let receipt = prove_info.receipt;

    // TODO: Implement code for retrieving receipt journal here.
    // For example:
    let _output: u32 = receipt.journal.decode().unwrap();

    // Print the output
    println!("Guest output: {}", _output);

    // The receipt was verified at the end of proving, but the below code is an
    // example of how someone else could verify this receipt.
    //receipt.verify(METHOD_ID).unwrap();
}
